name: Run Python Script Daily at 1 AM

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 1 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datetime requests==2.26.0 beautifulsoup4==4.10.0 cloudscraper selenium

    - name: Remove existing Chromedriver
      run: |
        sudo rm -f /usr/local/bin/chromedriver

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Install Chromedriver
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify Chrome and Chromedriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run Bitcoin ETF Scraper
      run: python bitcoin_etf_scraper.py

    - name: Run BTC Flows Coinglass
      run: python btc_flows_coinglass.py
